### ISSUE TITLE
CUDA error reported on GPU 0: device-side assert triggered (CUDA_ERROR_ASSERT)

### ISSUE THREAD

**Issue by Orion-wyc** [flexflow/FlexFlow#19]
@jiazhihao I am training AlexNet with cifar10 data_batch_1.bin on my server. I only use 2 GPUs and it seems that parameters on different GPUs may fail to synchronize. The label is -1 and logits in  _softmax_cross_entropy_calc_loss_ are nan (the same when using other batches). If I use synthetic data,it runs properly.

Thanks.

ERROR INFO:
...
acc_train_loss: inf train_accuracy: 9.38%(24/256)
acc_train_loss: inf train_accuracy: 8.01%(41/512)
../../src/ops/softmax.cu[0 - 7f3f69ffe700] {6}{gpu}: CUDA error reported on GPU 0: device-side assert triggered (CUDA_ERROR_ASSERT)
:226: void softmax_cross_entropy_calc_loss(const float *, const int *, PerfMetrics *, int, int): block: [0,0,0], thread: [96,0,0] Assertion `my_label >= 0` failed.
../../src/ops/softmax.cu:226: void softmax_cross_entropy_calc_loss(const float *, const int *, PerfMetrics *, int, int): block: [0,0,0], thread: [97,0,0] Assertion `my_label >= 0` failed.
../../src/ops/softmax.cu:226alexnet: /seu_share/home/yuchen/FlexFlow-test/FlexFlow/legion/runtime/realm/cuda/cuda_module.cc:234: bool Realm::Cuda::GPUStream::reap_events(): Assertion `0' failed.

Device RTX 2080ti *2 Ubuntu 18.04 Cuda10.5 cudnn7.6.5

**Comment by jiazhihao** [comment]
@Orion-wyc Thanks for reporting the bug. I have fixed a bug in the concatenation that caused the GPU failure. After the fix, it now works fine on multiple GPUs on my instance. Let me know if you still observe any failure.

**Comment by Orion-wyc** [comment]
@jiazhihao Wow, thanks for solving this issue. It runs properly on mutiple GPUs. And luckily, I noticed that it achieves better performance on convergence after fixing the bug. ヾ(*´▽‘*)ﾉ

PS: 
I have three question on the source code, so I sent you an e-mail (from orionXXX.yeah.net) several days ago. One of the problem has been solved in this issue. I think that some infomation in that e-mail is out-of-date and I will resend on to you. We can talking about it when you are at leisure, if possible. If you will, we can chat on wechat or other apps.
 
Sorry to bother. Thank you for your help.

**Comment by MiZhangWhuer** [comment]
> @Orion-wyc Thanks for reporting the bug. I have fixed a bug in the concatenation that caused the GPU failure. After the fix, it now works fine on multiple GPUs on my instance. Let me know if you still observe any failure.

Hi, zhihao, which part do you fixed? Can you provide more details?
