### ISSUE TITLE
Multinode test failing

### ISSUE THREAD

**Issue by gabrieleoliaro** [flexflow/FlexFlow#803]
The multinode test is currently failing. In particular, the `Multinode GPU Test with MPI` and `Multinode GPU Test with UCX` tests get stuck and make the corresponding CI jobs run forever, until they are interrupted by a timeout. On the other hand, the `Multinode GPU Test with native UCX` works well and finishes in about 1.5h.

Here is a link to the most recent CI run with the logs. The workflow has currently been disabled to prevent overusing the `flexflow-runner` instance.

**Comment by gabrieleoliaro** [comment]
@mengdiz97 would you have time to take a look at this?

**Comment by mengdiz97** [comment]
@gabrieleoliaro Sure, I will check it. Could you share the failed job link? Thanks!

**Comment by gabrieleoliaro** [comment]
@mengdiz97 here it is: https://github.com/flexflow/FlexFlow/actions/runs/5287711808

**Comment by mengdiz97** [comment]
Hi @gabrieleoliaro , could enable the multinode test for the PR #807 and further test because I did not find any errors in the log of the failed jobs. Thanks!

**Comment by gabrieleoliaro** [comment]
@mengdiz97 I have re-enabled the workflow. Feel free to edit the `multinode-test.yml` or run the workflow manually with workflow dispatch to test on the PR

**Comment by mengdiz97** [comment]
@gabrieleoliaro thanks! But I cannot find the `run workflow` button in Actions. Is there any permission issue?

**Comment by gabrieleoliaro** [comment]
@mengdiz97 I added you as a collaborator! Let me know if you can see the button now!

**Comment by mengdiz97** [comment]
@gabrieleoliaro Thanks! That works!

**Comment by mengdiz97** [comment]
I had some investigations and there are generally two kinds of errors:

1. libpython3.10.so: cannot open shared object file: No such file or directory
It should have been solved by commits in PR #807 .

2. timeout
- The phenomenon of the issue is that multinode test would get stuck somewhere after training starts and it seems like there is a deadlock. The issue only happens with GASNet and when multiple nodes are used.
- We updated the version of legion from 15b23c to 01675f to support native UCX in PR #700 . I downgraded the version of legion back to 15b23c and the training did not get stuck. Therefore, I guess it may be a issue related to legion and GASNet.
- Any ideas about how to check where the training is stuck or any suggestions about the version of legion we should use? @goliaro @eddy16112
