### ISSUE TITLE
[Inference] get `Cuda failure: 7` on IncMultiHeadAttention::compute_qkv_kernel(...)

### ISSUE THREAD

**Issue by huawei-lin** [flexflow/FlexFlow#806]
Hi, I try to run tests/inference_tests.sh on 2 A100 40GB, but got below error information.

```
+ set -e
+ mkdir -p ../inference/prompt
+ echo '["Give three tips for staying healthy."]'
+ mkdir -p ../inference/output
+ ../build/inference/spec_infer/spec_infer -ll:gpu 2 -ll:fsize 35000 -ll:zsize 30000 -llm-model llama -llm-weight ../inference/weights/llama_7B_weights_half/ -llm-config ../inference/models/configs/llama_7B.json -ssm-model llama -ssm-weight ../inference/weights/llama_160M_weights_half/ -ssm-config ../inference/models/configs/llama_160M.json -tokenizer ../inference/tokenizer/tokenizer.model -prompt ../inference/prompt/test.json -output-file ../inference/output/spec_inference_llama_half.txt
Note: inference currently only supports data/pipeline parallel.
[Warning] a potentially unnecessary  inter-GPU copy of size 262144
Note: inference currently only supports data/pipeline parallel.
Cuda failure: 7
/home/hl3352/LLM/FlexFlow/src/ops/inc_multihead_self_attention.cu:195
Aborting...
spec_infer: /home/hl3352/LLM/FlexFlow/src/ops/inc_multihead_self_attention.cu:195: void FlexFlow::Kernels::IncMultiHeadAttention::compute_qkv_kernel(const FlexFlow::IncMultiHeadSelfAttentionMeta*, const FlexFlow::BatchConfig*, const DT*, const DT*, DT*, const DT*, cudaStream_t) [with DT = __half; cudaStream_t = CUstream_st*]: Assertion `false' failed.
inference_tests.sh: line 39: 20880 Aborted                 ../build/inference/spec_infer/spec_infer -ll:gpu 2 -ll:fsize 35000 -ll:zsize 30000 -llm-model llama -llm-weight ../inference/weights/llama_7B_weights_half/ -llm-config ../inference/models/configs/llama_7B.json -ssm-model llama -ssm-weight ../inference/weights/llama_160M_weights_half/ -ssm-config ../inference/models/configs/llama_160M.json -tokenizer ../inference/tokenizer/tokenizer.model -prompt ../inference/prompt/test.json -output-file ../inference/output/spec_inference_llama_half.txt
```

GPU and nvcc info:
```
Sun Jun 25 14:27:32 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.11    Driver Version: 525.60.11    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-PCI...  On   | 00000000:3B:00.0 Off |                    0 |
| N/A   36C    P0    34W / 250W |      0MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-PCI...  On   | 00000000:5E:00.0 Off |                    0 |
| N/A   30C    P0    31W / 250W |      0MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

(flexflow) hl3352:FlexFlow/ (inference*) $ nvcc -V                                                                                                                [14:30:53]
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Feb__7_19:32:13_PST_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0
```

Output:
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
WARNING:

You should always run with libnvidia-ml.so that is installed with your
NVIDIA Display Driver. By default it's installed in /usr/lib and /usr/lib64.
libnvidia-ml.so in GDK package is a stub library that is attached only for
build purposes (e.g. machine that you build your application doesn't have
to have Display Driver installed).
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Linked to libnvidia-ml library at wrong path : /home/hl3352/anaconda3/envs/flexflow/lib/stubs/libnvidia-ml.so

[0 - 7ff8677e9700]    0.180007 {3}{Mapper}: Enabled Control Replication Optimizations.
[0 - 7ff8677e9700]    0.180131 {3}{Mapper}: Enabled Control Replication Optimizations.
[0 - 7ff8677e9700]    0.180140 {3}{Mapper}: Enabled Control Replication Optimizations.
workSpaceSize (1024 MB)
workSpaceSize (1024 MB)
LLAMA Config:
n_layers: 32
vocab_size: 32000
n_heads: 32
dim: 4096
multiple_of: 256
norm_eps: 1e-06
total_requests: 2560
incremental_mode: 1
max_seq_len: 256
max_num_tokens: 64
max_beam_width: 1
max_beam_depth: 8
hidden_dim: 11008
------start compile ----------
num_nodes = 1 num_gpus_per_node = 2
optimal_views.size = 357
views.size() = 357
Deserialized Views...
node[5000556]: type(Add_5000556) view(1 2 0)  inEdge(node(5000555) idx(0)) inEdge(node(5000548) idx(0))
node[5000557]: type(RMSNorm_5000557) view(1 2 0)  inEdge(node(5000556) idx(0))
node[5000558]: type(TreeIncMultiHeadSelfAttention_5000558) view(1 2 0)  inEdge(node(5000557) idx(0))
node[5000559]: type(Add_5000559) view(1 2 0)  inEdge(node(5000558) idx(0)) inEdge(node(5000556) idx(0))
node[5000560]: type(RMSNorm_5000560) view(1 2 0)  inEdge(node(5000559) idx(0))
node[5000562]: type(Dense_5000562) view(1 2 0)  inEdge(node(5000560) idx(0))
node[5000561]: type(Dense_5000561) view(1 2 0)  inEdge(node(5000560) idx(0))
node[5000563]: type(Sigmoid_5000563) view(1 2 0)  inEdge(node(5000562) idx(0))
node[5000564]: type(Mul_5000564) view(1 2 0)  inEdge(node(5000563) idx(0)) inEdge(node(5000562) idx(0))
node[5000565]: type(Mul_5000565) view(1 2 0)  inEdge(node(5000561) idx(0)) inEdge(node(5000564) idx(0))
node[5000566]: type(Dense_5000566) view(1 2 0)  inEdge(node(5000565) idx(0))
node[5000567]: type(Add_5000567) view(1 2 0)  inEdge(node(5000566) idx(0)) inEdge(node(5000559) idx(0))
node[5000568]: type(RMSNorm_5000568) view(1 2 0)  inEdge(node(5000567) idx(0))
node[5000569]: type(TreeIncMultiHeadSelfAttention_5000569) view(1 2 0)  inEdge(node(5000568) idx(0))
node[5000570]: type(Add_5000570) view(1 2 0)  inEdge(node(5000569) idx(0)) inEdge(node(5000567) idx(0))
.
.
.
init linear (input): in_dim(3072) out_dim(768) batch_size(64)
init linear (input): in_dim(768) out_dim(3072) batch_size(64)
init linear (input): in_dim(768) out_dim(3072) batch_size(64)
init linear (input): in_dim(3072) out_dim(768) batch_size(64)
init linear (input): in_dim(768) out_dim(3072) batch_size(64)
init linear (input): in_dim(768) out_dim(3072) batch_size(64)
init linear (input): in_dim(3072) out_dim(768) batch_size(64)
init linear (input): in_dim(768) out_dim(32000) batch_size(64)
Register new model with id: 0
Prompt[0]: Give three tips for staying healthy.
25538
2211
25562
363
7952
292
9045
29891
29889
Num of models: 1
[0 - 7ff8677e9700]   86.444583 {3}{RequestManager}: New request tokens: 0 25538 2211 25562 363 7952 292 9045 29891 29889
==================
Register Batch Config with Model 0
[0 - 7ff8677e9700]   86.444660 {3}{InferenceManager}: mode(2002) num_active_tokens(10) num_active_requests(1)
```

CMake Config:
```
[hl3352@clx-a-01 build]$ ../config/config.linux
CUDA_PATH=/home/hl3352/anaconda3/envs/flexflow/lib/stubs cmake -DCUDA_USE_STATIC_CUDA_RUNTIME=OFF -DCMAKE_C_COMPILER=/.autofs/tools/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/gcc-9.3.0-hufzekvjjthuym26f7awxnf24j52uypk/bin/gcc -DCMAKE_CXX_COMPILER=/.autofs/tools/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/gcc-9.3.0-hufzekvjjthuym26f7awxnf24j52uypk/bin/g++ -DINFERENCE_TESTS=OFF -DLIBTORCH_PATH=/home/hl3352/LLM/libtorch -DCMAKE_BUILD_TYPE=Release -DFF_CUDA_ARCH=all -DCUDA_PATH=/home/hl3352/anaconda3/envs/flexflow -DCUDNN_PATH=/usr/local/cuda -DFF_USE_PYTHON=ON -DFF_USE_NCCL=ON -DFF_BUILD_ALL_EXAMPLES=OFF -DFF_BUILD_ALL_INFERENCE_EXAMPLES=ON -DFF_USE_PREBUILT_LEGION=OFF -DFF_USE_PREBUILT_NCCL=ON -DFF_USE_ALL_PREBUILT_LIBRARIES=OFF -DFF_BUILD_UNIT_TESTS=OFF -DFF_USE_AVX2=OFF -DFF_MAX_DIM=5 -DLEGION_MAX_RETURN_SIZE=131072 -DROCM_PATH=/opt/rocm -DFF_GPU_BACKEND=cuda ../config/../
-- FF_GASNET_CONDUIT: mpi
-- Linux Version: 7.9
-- CPU architecture: x86_64
-- ZLIB libraries : /.autofs/tools/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/zlib-1.2.11-7xsa4oqvgg2255vgsiohjlx2xbtaexld/lib/libz.so
-- CUDA_VERSION: 12.1
-- CUDA root path : /home/hl3352/anaconda3/envs/flexflow
-- CUDA include path : /home/hl3352/anaconda3/envs/flexflow/include
-- CUDA runtime libraries :
-- CUDA driver libraries : /home/hl3352/anaconda3/envs/flexflow/lib/stubs/libcuda.so
-- CUBLAS libraries : /home/hl3352/anaconda3/envs/flexflow/lib/libcublas.so
-- CURAND libraries : /home/hl3352/anaconda3/envs/flexflow/lib/libcurand.so
-- CUDA Arch : 60,61,62,70,72,75,80,86
-- CUDA_GENCODE: -gencode arch=compute_60,code=sm_60;-gencode arch=compute_61,code=sm_61;-gencode arch=compute_62,code=sm_62;-gencode arch=compute_70,code=sm_70;-gencode arch=compute_72,code=sm_72;-gencode arch=compute_75,code=sm_75;-gencode arch=compute_80,code=sm_80;-gencode arch=compute_86,code=sm_86
-- CUDNN include : /home/hl3352/anaconda3/envs/flexflow/include
-- CUDNN libraries : /home/hl3352/anaconda3/envs/flexflow/lib/libcudnn.so
-- Building NCCL from source
NCCL_BUILD_NVCC_GENCODE: NVCC_GENCODE=-gencode arch=compute_60,code=sm_60;NVCC_GENCODE=-gencode arch=compute_61,code=sm_61;NVCC_GENCODE=-gencode arch=compute_62,code=sm_62;NVCC_GENCODE=-gencode arch=compute_70,code=sm_70;NVCC_GENCODE=-gencode arch=compute_72,code=sm_72;NVCC_GENCODE=-gencode arch=compute_75,code=sm_75;NVCC_GENCODE=-gencode arch=compute_80,code=sm_80;NVCC_GENCODE=-gencode arch=compute_86,code=sm_86
-- NCCL install dir: /home/hl3352/LLM/FlexFlow/build/deps/nccl
-- Building Legion from source
-- GASNET ROOT:
-- Version string from git: legion-23.03.0-4376-g01675f6
-- Using the single-header code from /home/hl3352/LLM/FlexFlow/build/_deps/json-src/single_include/
-- FlexFlow MAX_DIM: 5
-- LEGION_MAX_RETURN_SIZE: 131072
-- system-nameLinux
-- VERSION: 0.2.00
-- pybind11 v2.6.2
-- Configuring done (1.8s)
-- Generating done (1.6s)
-- Build files have been written to: /home/hl3352/LLM/FlexFlow/build
```

Inference_test.sh:
```
#! /usr/bin/env bash
set -x
set -e

cleanup() {
    rm -rf ../inference/prompt ../inference/weights ../inference/tokenizer ../inference/output
}

# Enable model parallelism tests, if desired
TENSOR_PARALLELISM_TESTS=${TENSOR_PARALLELISM_TESTS:-OFF}

# Create test prompt file
mkdir -p ../inference/prompt
echo '["Give three tips for staying healthy."]' > ../inference/prompt/test.json

# Create output folder
mkdir -p ../inference/output

###############################################################################################
############################ Speculative inference tests ######################################
###############################################################################################

# LLAMA (half precision)
../build/inference/spec_infer/spec_infer -ll:gpu 2 -ll:fsize 35000 -ll:zsize 30000 -llm-model llama -llm-weight ../inference/weights/llama_7B_weights_half/ -llm-config ../inference/models/configs/llama_7B.json -ssm-model llama -ssm-weight ../inference/weights/llama_160M_weights_half/ -ssm-config ../inference/models/configs/llama_160M.json -tokenizer ../inference/tokenizer/tokenizer.model -prompt ../inference/prompt/test.json -output-file ../inference/output/spec_inference_llama_half.txt

```

**Comment by jiazhihao** [comment]
Can you reduce `fsize` to 30000 and rerun the test?

**Comment by huawei-lin** [comment]
@jiazhihao Thank you for your reponse. `Cuda failure: 7` for `fsize 30000`

**Comment by huawei-lin** [comment]
Problem solved by downgrading cuda 12.1 to 11.8
